server:
  port: 8701
spring:
  application:
    name: feign-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://macro:111111@127.0.0.1:8001/eureka/
feign:
  hystrix:
    enabled: true