server:
  port: 8001
spring:
  application:
    name: eureka-server
  security:
    user:
      name: macro
      password: 111111
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
