server:
  port: 8201
spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://macro:111111@127.0.0.1:8001/eureka/,http://macro:111111@127.0.0.1:8002/eureka/,http://macro:111111@127.0.0.1:8003/eureka/