server:
  port: 8301
spring:
  application:
    name: ribbon-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://macro:111111@127.0.0.1:8002/eureka/,http://macro:111111@127.0.0.1:8003/eureka/
service-url:
  uer-service: http://USER-SERVICE
